In [1]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

c:\Users\princ\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
model=DiscreteBayesianNetwork([('Rain','Traffic'),('Traffic','Late')])
cpd_rain=TabularCPD('Rain',2,[[0.6],[0.4]])
model.add_cpds(cpd_rain)
print(cpd_rain)

+---------+-----+
| Rain(0) | 0.6 |
+---------+-----+
| Rain(1) | 0.4 |
+---------+-----+

In [3]:
dataset=pd.read_csv(r"C:\Users\princ\Downloads\archive (1)\dataset.csv")
dataset

,Disease,Symptom_0,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16
0,AIDS,muscle_wasting,patches_in_throat,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AIDS,patches_in_throat,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AIDS,muscle_wasting,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AIDS,muscle_wasting,patches_in_throat,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AIDS,muscle_wasting,patches_in_throat,high_fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,Varicose veins,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels,prominent_veins_on_calf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,Varicose veins,fatigue,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels,prominent_veins_on_calf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,Varicose veins,fatigue,cramps,bruising,obesity,swollen_legs,prominent_veins_on_calf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,Varicose veins,fatigue,cramps,bruising,swollen_legs,swollen_blood_vessels,prominent_veins_on_calf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,Varicose veins,fatigue,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dataset['Disease'].value_counts()

Disease
Chicken pox                      10
Dengue                           10
Hepatitis D                      10
Migraine                         10
Covid                             9
Hepatitis B                       9
Diabetes                          9
Hepatitis A                       9
Hepatitis E                       9
Common Cold                       9
Pneumonia                         9
Jaundice                          9
Typhoid                           9
Tuberculosis                      9
Hypoglycemia                      9
Hyperthyroidism                   9
Chronic cholestasis               8
Alcoholic hepatitis               8
Varicose veins                    8
Malaria                           8
Hypothyroidism                    8
Psoriasis                         7
Paroxysmal Positional Vertigo     7
Bronchial Asthma                  7
Osteoarthritis                    7
Peptic ulcer disease              7
Hepatitis C                       7
GERD                              7
Dimorphic hemorrhoids(piles)      6
Cervical spondylosis              6
Arthritis                         6
Impetigo                          6
Hypertension                      6
Drug Reaction                     6
Allergy                           5
Acne                              5
AIDS                              5
Fungal infection                  5
Heart attack                      5
Gastroenteritis                   5
Paralysis (brain hemorrhage)      5
Urinary tract infection           5
Name: count, dtype: int64

In [5]:
dataset[dataset['Disease']=='Chronic cholestasis']

,Disease,Symptom_0,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16
52,Chronic cholestasis,vomiting,yellowish_skin,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Chronic cholestasis,itching,vomiting,yellowish_skin,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Chronic cholestasis,itching,vomiting,yellowish_skin,nausea,loss_of_appetite,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Chronic cholestasis,itching,vomiting,yellowish_skin,nausea,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Chronic cholestasis,itching,vomiting,yellowish_skin,nausea,loss_of_appetite,abdominal_pain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Chronic cholestasis,itching,vomiting,yellowish_skin,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Chronic cholestasis,itching,vomiting,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Chronic cholestasis,itching,yellowish_skin,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv(r"C:\Users\princ\Downloads\Disease and symptoms dataset 2023\Disease and symptoms dataset 2023\Disease and symptoms dataset.csv")
df2=df['diseases'].unique()
df2.sort()
print(df2)

['abdominal aortic aneurysm' 'abdominal hernia' 'abscess of nose'
 'abscess of the lung' 'abscess of the pharynx' 'acanthosis nigricans'
 'acariasis' 'achalasia' 'acne' 'actinic keratosis' 'acute bronchiolitis'
 'acute bronchitis' 'acute bronchospasm'
 'acute fatty liver of pregnancy (aflp)' 'acute glaucoma'
 'acute kidney injury' 'acute otitis media' 'acute pancreatitis'
 'acute respiratory distress syndrome (ards)' 'acute sinusitis'
 'acute stress reaction' 'adhesive capsulitis of the shoulder'
 'adjustment reaction' 'adrenal adenoma' 'adrenal cancer' 'alcohol abuse'
 'alcohol intoxication' 'alcohol withdrawal' 'alcoholic liver disease'
 'allergy' 'allergy to animals' 'alopecia' 'alzheimer disease' 'amblyopia'
 'amyloidosis' 'amyotrophic lateral sclerosis (als)' 'anal fissure'
 'anal fistula' 'anemia' 'anemia due to chronic kidney disease'
 'anemia due to malignancy' 'anemia of chronic disease' 'angina'
 'ankylosing spondylitis' 'anxiety' 'aortic valve disease' 'aphakia'
 'aphthous ulcer' 'aplastic anemia' 'appendicitis' 'arrhythmia'
 'arthritis of the hip' 'ascending cholangitis' 'asperger syndrome'
 'aspergillosis' 'asthma' 'astigmatism' 'atelectasis' "athlete's foot"
 'atonic bladder' 'atrial fibrillation' 'atrial flutter'
 'atrophic skin condition' 'atrophic vaginitis'
 'atrophy of the corpus cavernosum'
 'attention deficit hyperactivity disorder (adhd)' 'autism'
 'autonomic nervous system disorder' 'avascular necrosis' 'balanitis'
 'bell palsy' 'benign kidney cyst'
 'benign paroxysmal positional vertical (bppv)'
 'benign prostatic hyperplasia (bph)'
 'benign vaginal discharge (leukorrhea)' 'bipolar disorder' 'birth trauma'
 'bladder cancer' 'bladder disorder' 'bladder obstruction' 'blepharitis'
 'blepharospasm' 'bone cancer' 'bone disorder'
 'bone spur of the calcaneous' 'brachial neuritis' 'brain cancer'
 'breast cancer' 'breast cyst' 'breast infection (mastitis)'
 'broken tooth' 'bunion' 'burn' 'bursitis' 'callus'
 'carbon monoxide poisoning' 'carcinoid syndrome' 'cardiac arrest'
 'cardiomyopathy' 'carpal tunnel syndrome' 'cat scratch disease'
 'cataract' 'celiac disease' 'cellulitis or abscess of mouth'
 'central atherosclerosis' 'central retinal artery or vein occlusion'
 'cerebral edema' 'cerebral palsy' 'cervical cancer' 'cervical disorder'
 'cervicitis' 'chalazion' 'chickenpox' 'chlamydia' 'cholecystitis'
 'choledocholithiasis' 'cholesteatoma' 'chondromalacia of the patella'
 'chorioretinitis' 'chronic back pain' 'chronic constipation'
 'chronic glaucoma'
 'chronic inflammatory demyelinating polyneuropathy (cidp)'
 'chronic kidney disease' 'chronic knee pain'
 'chronic obstructive pulmonary disease (copd)' 'chronic otitis media'
 'chronic pain disorder' 'chronic pancreatitis' 'chronic rheumatic fever'
 'chronic sinusitis' 'chronic ulcer' 'cirrhosis'
 'coagulation (bleeding) disorder' 'cold sore' 'colonic polyp'
 'colorectal cancer' 'common cold' 'complex regional pain syndrome'
 'concussion' 'conduct disorder' 'conductive hearing loss'
 'congenital heart defect' 'congenital malformation syndrome'
 'conjunctivitis' 'conjunctivitis due to allergy'
 'conjunctivitis due to bacteria' 'conjunctivitis due to virus'
 'connective tissue disorder' 'contact dermatitis' 'conversion disorder'
 'cornea infection' 'corneal abrasion' 'corneal disorder'
 'coronary atherosclerosis' 'cranial nerve palsy' 'crohn disease' 'croup'
 'crushing injury' 'cryptococcosis' 'cryptorchidism' 'cushing syndrome'
 'cyst of the eyelid' 'cystic fibrosis' 'cysticercosis' 'cystitis'
 'de quervain disease' 'decubitus ulcer' 'deep vein thrombosis (dvt)'
 'degenerative disc disease' 'delirium' 'dementia' 'dengue fever'
 'dental caries' 'depression' 'dermatitis due to sun exposure'
 'developmental disability' 'deviated nasal septum' 'diabetes'
 'diabetes insipidus' 'diabetic ketoacidosis' 'diabetic kidney disease'
 'diabetic peripheral neuropathy' 'diabetic retinopathy' 'diaper rash'
 'dislocation of the ankle' 'dislocation of the elbow'
 'dislocation of the finger' 'dislocation of the foot'
 'dislocation of the hip' 'dislocation of the knee'
 'dislocation of the patella' 'dislocation of the shoulder'
 'dislocation of the vertebra' 'dislocation of the wrist'
 'dissociative disorder' 'diverticulitis' 'diverticulosis' 'down syndrome'
 'drug abuse' 'drug abuse (barbiturates)' 'drug abuse (cocaine)'
 'drug abuse (methamphetamine)' 'drug abuse (opioids)'
 'drug poisoning due to medication' 'drug reaction' 'drug withdrawal'
 'dry eye of unknown cause' 'dumping syndrome' 'dyshidrosis'
 'dysthymic disorder' 'ear drum damage' 'ear wax impaction'
 'eating disorder' 'ectopic pregnancy' 'ectropion' 'eczema'
 'edward syndrome' 'emphysema' 'empyema' 'encephalitis' 'endocarditis'
 'endometrial cancer' 'endometrial hyperplasia' 'endometriosis'
 'endophthalmitis' 'envenomation from spider or animal bite' 'ependymoma'
 'epididymitis' 'epidural hemorrhage' 'epilepsy' 'erectile dysfunction'
 'erythema multiforme' 'esophageal cancer' 'esophageal varices'
 'esophagitis' 'essential tremor'
 'eustachian tube dysfunction (ear disorder)'
 'extrapyramidal effect of drugs' 'eye alignment disorder'
 'factitious disorder' 'female genitalia infection'
 'female infertility of unknown cause' 'fetal alcohol syndrome'
 'fibroadenoma' 'fibrocystic breast disease' 'fibromyalgia' 'flat feet'
 'floaters' 'flu' 'fluid overload' 'folate deficiency' 'food allergy'
 'foreign body in the ear' 'foreign body in the eye'
 'foreign body in the gastrointestinal tract' 'foreign body in the nose'
 'foreign body in the throat' 'foreign body in the vagina'
 'fracture of the ankle' 'fracture of the arm'
 'fracture of the facial bones' 'fracture of the finger'
 'fracture of the foot' 'fracture of the hand' 'fracture of the jaw'
 'fracture of the leg' 'fracture of the neck' 'fracture of the patella'
 'fracture of the pelvis' 'fracture of the rib' 'fracture of the shoulder'
 'fracture of the skull' 'fracture of the vertebra' 'friedrich ataxia'
 'frostbite' 'fungal infection of the hair' 'fungal infection of the skin'
 'g6pd enzyme deficiency' 'galactorrhea of unknown cause' 'gallstone'
 'ganglion cyst' 'gas gangrene' 'gastritis' 'gastroduodenal ulcer'
 'gastroesophageal reflux disease (gerd)' 'gastrointestinal hemorrhage'
 'gastroparesis' 'genital herpes' 'gestational diabetes' 'glaucoma'
 'glucocorticoid deficiency' 'goiter' 'gonorrhea' 'gout'
 'granuloma inguinale' 'graves disease' 'guillain barre syndrome'
 'gum disease' 'gynecomastia' 'hammer toe' 'hashimoto thyroiditis'
 'head and neck cancer' 'head injury' 'headache after lumbar puncture'
 'heart attack' 'heart block' 'heart contusion' 'heart failure'
 'heat exhaustion' 'heat stroke' 'hemangioma' 'hemarthrosis' 'hematoma'
 'hemiplegia' 'hemochromatosis' 'hemolytic anemia' 'hemophilia'
 'hemorrhoids' 'hepatic encephalopathy' 'hepatitis due to a toxin'
 'herniated disk' 'herpangina' 'hiatal hernia' 'hidradenitis suppurativa'
 'high blood pressure' 'hirschsprung disease' 'hirsutism' 'histoplasmosis'
 'hormone disorder' 'hpv' 'human immunodeficiency virus infection (hiv)'
 'huntington disease' 'hydatidiform mole' 'hydrocele of the testicle'
 'hydrocephalus' 'hydronephrosis' 'hypercalcemia' 'hypercholesterolemia'
 'hyperemesis gravidarum' 'hypergammaglobulinemia' 'hyperhidrosis'
 'hyperkalemia' 'hyperlipidemia' 'hypernatremia' 'hyperopia'
 'hyperosmotic hyperketotic state' 'hypertension of pregnancy'
 'hypertensive heart disease'
 'hypertrophic obstructive cardiomyopathy (hocm)' 'hypocalcemia'
 'hypoglycemia' 'hypokalemia' 'hyponatremia' 'hypothermia'
 'hypothyroidism' 'hypovolemia' 'idiopathic absence of menstruation'
 'idiopathic excessive menstruation' 'idiopathic infrequent menstruation'
 'idiopathic irregular menstrual cycle' 'idiopathic nonmenstrual bleeding'
 'idiopathic painful menstruation' 'ileus' 'impetigo'
 'impulse control disorder' 'indigestion' 'induced abortion'
 'infection of open wound' 'infectious gastroenteritis' 'ingrown toe nail'
 'inguinal hernia' 'injury of the ankle' 'injury to internal organ'
 'injury to the abdomen' 'injury to the arm' 'injury to the face'
 'injury to the finger' 'injury to the hand' 'injury to the hip'
 'injury to the knee' 'injury to the leg' 'injury to the shoulder'
 'injury to the spinal cord' 'injury to the trunk' 'insect bite'
 'insulin overdose' 'interstitial lung disease'
 'intertrigo (skin condition)' 'intestinal cancer' 'intestinal disease'
 'intestinal malabsorption' 'intestinal obstruction'
 'intracerebral hemorrhage' 'intracranial abscess'
 'intracranial hemorrhage' 'intussusception' 'iridocyclitis'
 'iron deficiency anemia' 'irritable bowel syndrome'
 'ischemia of the bowel' 'ischemic heart disease'
 'itching of unknown cause' 'jaw disorder' 'joint effusion'
 'juvenile rheumatoid arthritis' 'kaposi sarcoma' 'kidney cancer'
 'kidney disease due to longstanding hypertension' 'kidney failure'
 'kidney stone' 'knee ligament or meniscus tear' 'labyrinthitis'
 'lactose intolerance' 'laryngitis' 'lateral epicondylitis (tennis elbow)'
 'leukemia' 'lewy body dementia' 'lice' 'lichen planus' 'lichen simplex'
 'lipoma' 'liver cancer' 'liver disease' 'lumbago' 'lung cancer'
 'lung contusion' 'lyme disease' 'lymphadenitis' 'lymphangitis'
 'lymphedema' 'lymphogranuloma venereum' 'lymphoma' 'macular degeneration'
 'magnesium deficiency' 'malaria' 'male genitalia infection'
 'malignant hypertension' 'marijuana abuse' 'mastectomy' 'mastoiditis'
 'meckel diverticulum' 'melanoma' 'meniere disease' 'meningioma'
 'meningitis' 'menopause' 'metabolic disorder' 'metastatic cancer'
 'migraine' 'missed abortion' 'mitral valve disease' 'mittelschmerz'
 'molluscum contagiosum' 'mononeuritis' 'mononucleosis' 'moyamoya disease'
 'mucositis' 'multiple myeloma' 'multiple sclerosis' 'mumps'
 'muscle spasm' 'muscular dystrophy' 'myasthenia gravis'
 'myelodysplastic syndrome' 'myocarditis' 'myoclonus' 'myopia' 'myositis'
 'narcolepsy' 'nasal polyp' 'necrotizing fasciitis' 'neonatal jaundice'
 'nerve impingement near the shoulder' 'neuralgia' 'neurofibromatosis'
 'neuropathy due to drugs' 'neurosis' 'nonalcoholic liver disease (nash)'
 'noninfectious gastroenteritis' 'normal pressure hydrocephalus'
 'nose disorder' 'obesity' 'obsessive compulsive disorder (ocd)'
 'obstructive sleep apnea (osa)' 'omphalitis' 'onychomycosis'
 'open wound due to trauma' 'open wound from surgical incision'
 'open wound of the abdomen' 'open wound of the arm'
 'open wound of the back' 'open wound of the cheek'
 'open wound of the chest' 'open wound of the ear' 'open wound of the eye'
 'open wound of the face' 'open wound of the finger'
 'open wound of the foot' 'open wound of the hand'
 'open wound of the head' 'open wound of the jaw' 'open wound of the knee'
 'open wound of the lip' 'open wound of the mouth'
 'open wound of the neck' 'open wound of the nose'
 'open wound of the shoulder' 'oppositional disorder' 'optic neuritis'
 'oral leukoplakia' 'oral mucosal lesion' 'oral thrush (yeast infection)'
 'orbital cellulitis' 'orthostatic hypotension' 'osteoarthritis'
 'osteochondroma' 'osteochondrosis' 'osteomyelitis' 'osteoporosis'
 "otitis externa (swimmer's ear)" 'otitis media' 'otosclerosis'
 'ovarian cancer' 'ovarian cyst' 'ovarian torsion' 'overflow incontinence'
 'pain after an operation' 'pain disorder affecting the neck'
 'pancreatic cancer' 'panic attack' 'panic disorder' 'parasitic disease'
 'parathyroid adenoma' 'parkinson disease' 'paronychia'
 'paroxysmal supraventricular tachycardia'
 'paroxysmal ventricular tachycardia' 'pelvic fistula'
 'pelvic inflammatory disease' 'pelvic organ prolapse' 'pemphigus'
 'pericarditis' 'peripheral arterial disease'
 'peripheral arterial embolism' 'peripheral nerve disorder'
 'perirectal infection' 'peritonitis' 'peritonsillar abscess'
 'persistent vomiting of unknown cause' 'personality disorder'
 'peyronie disease' 'pharyngitis' 'phimosis' 'pilonidal cyst' 'pinguecula'
 'pinworm infection' 'pituitary adenoma' 'pituitary disorder'
 'pityriasis rosea' 'placenta previa' 'placental abruption'
 'plantar fasciitis' 'pleural effusion' 'pneumoconiosis' 'pneumonia'
 'pneumothorax' 'poisoning due to analgesics'
 'poisoning due to anticonvulsants' 'poisoning due to antidepressants'
 'poisoning due to antihypertensives'
 'poisoning due to antimicrobial drugs' 'poisoning due to antipsychotics'
 'poisoning due to ethylene glycol' 'poisoning due to gas'
 'poisoning due to opioids' 'poisoning due to sedatives'
 'polycystic kidney disease' 'polycystic ovarian syndrome (pcos)'
 'polycythemia vera' 'polymyalgia rheumatica'
 'post-traumatic stress disorder (ptsd)' 'postoperative infection'
 'postpartum depression' 'preeclampsia' 'pregnancy'
 'premature atrial contractions (pacs)' 'premature ovarian failure'
 'premature rupture of amniotic membrane'
 'premature ventricular contractions (pvcs)'
 'premenstrual tension syndrome' 'presbyacusis' 'presbyopia' 'priapism'
 'primary immunodeficiency' 'primary insomnia' 'primary kidney disease'
 'primary thrombocythemia' 'problem during pregnancy' 'prostate cancer'
 'prostatitis' 'protein deficiency' 'pseudohypoparathyroidism'
 'pseudotumor cerebri' 'psoriasis' 'psychosexual disorder'
 'psychotic disorder' 'pterygium' 'pulmonary congestion'
 'pulmonary embolism' 'pulmonary eosinophilia' 'pulmonary fibrosis'
 'pulmonary hypertension' 'pulmonic valve disease' 'pyelonephritis'
 'pyloric stenosis' 'pyogenic skin infection' 'raynaud disease'
 'reactive arthritis' 'rectal disorder' 'restless leg syndrome'
 'retinal detachment' 'retinopathy due to high blood pressure'
 'rhabdomyolysis' 'rheumatic fever' 'rheumatoid arthritis'
 'rocky mountain spotted fever' 'rosacea' 'rotator cuff injury'
 'salivary gland disorder' 'sarcoidosis' 'scabies' 'scar' 'scarlet fever'
 'schizophrenia' 'sciatica' 'scleritis' 'scleroderma' 'scoliosis' 'scurvy'
 'seasonal allergies (hay fever)' 'sebaceous cyst' 'seborrheic dermatitis'
 'seborrheic keratosis' 'sensorineural hearing loss' 'sepsis'
 'septic arthritis' 'shingles (herpes zoster)' 'sialoadenitis'
 'sick sinus syndrome' 'sickle cell anemia' 'sickle cell crisis'
 'sinus bradycardia' 'sjogren syndrome' 'skin cancer' 'skin disorder'
 'skin pigmentation disorder' 'skin polyp' 'smoking or tobacco addiction'
 'social phobia' 'soft tissue sarcoma' 'somatization disorder'
 'spermatocele' 'spherocytosis' 'spina bifida' 'spinal stenosis'
 'spinocerebellar ataxia' 'spondylitis' 'spondylolisthesis' 'spondylosis'
 'spontaneous abortion' 'sporotrichosis' 'sprain or strain'
 'stenosis of the tear duct' 'stomach cancer' 'strep throat'
 'stress incontinence' 'stricture of the esophagus' 'stroke' 'stye'
 'subacute thyroiditis' 'subarachnoid hemorrhage'
 'subconjunctival hemorrhage' 'subdural hemorrhage'
 'substance-related mental disorder'
 'syndrome of inappropriate secretion of adh (siadh)' 'syphilis'
 'syringomyelia' 'systemic lupus erythematosis (sle)' 'teething syndrome'
 'temporary or benign blood in urine' 'temporomandibular joint disorder'
 'tendinitis' 'tension headache' 'testicular cancer' 'testicular disorder'
 'testicular torsion' 'thalassemia' 'thoracic aortic aneurysm'
 'thoracic outlet syndrome' 'threatened pregnancy' 'thrombocytopenia'
 'thrombophlebitis' 'thyroid cancer' 'thyroid disease' 'thyroid nodule'
 'tic (movement) disorder' 'tietze syndrome' 'tinnitus of unknown cause'
 'tonsillar hypertrophy' 'tonsillitis' 'tooth abscess' 'tooth disorder'
 'torticollis' 'tourette syndrome' 'toxic multinodular goiter'
 'toxoplasmosis' 'tracheitis' 'transient ischemic attack' 'trichiasis'
 'trichinosis' 'trichomonas infection' 'tricuspid valve disease'
 'trigeminal neuralgia' 'trigger finger (finger disorder)' 'tuberculosis'
 'tuberous sclerosis' 'turner syndrome' 'typhoid fever'
 'ulcerative colitis' 'urethral disorder' 'urethral stricture'
 'urethral valves' 'urethritis' 'urge incontinence'
 'urinary tract infection' 'urinary tract obstruction' 'uterine atony'
 'uterine cancer' 'uterine fibroids' 'uveitis' 'vacterl syndrome'
 'vaginal cyst' 'vaginal yeast infection' 'vaginismus' 'vaginitis'
 'valley fever' 'varicocele of the testicles' 'varicose veins'
 'vasculitis' 'venous insufficiency' 'vertebrobasilar insufficiency'
 'vesicoureteral reflux' 'viral exanthem' 'viral hepatitis' 'viral warts'
 'vitamin a deficiency' 'vitamin b12 deficiency' 'vitamin d deficiency'
 'vitreous degeneration' 'vitreous hemorrhage' 'vocal cord polyp'
 'volvulus' 'von willebrand disease' 'vulvar cancer' 'vulvar disorder'
 'vulvodynia' 'wernicke korsakoff syndrome' 'white blood cell disease'
 'whooping cough' 'wilson disease' 'yeast infection' 'zenker diverticulum']

In [13]:
df=df[df['diseases'].isin(['common cold','flu','food allergy','migraine','urinary tract infection','seasonal allergies (hay fever)','tonsillitis','dermatitis due to sun exposure','heat stroke','heat exhaustion','ear wax impaction','drug reaction','drug poisoning due to medication','conjunctivitis','anemia','muscle spasm','cold sore','yeast infection','high blood pressure','chicken pox','dengue fever','malaria','typhoid disease','frostbite'])]
df=df.loc[:,(df!=0).any(axis=0)]
print(df.shape)
df.to_csv(r"C:\Users\princ\Downloads\new_disease_dataset.csv")

(9642, 100)